import React, { useContext } from "react";
import { Navigate, Route, Routes } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";
import PortalLayout from "../components/PortalLayout/PortalLayout";
import Home from "../pages/Home/Home"; import Dashboard from "../pages/Dashboard/Dashboard"; import Login from "../pages/Auth/Login"; import Register from "../pages/Auth/Register"; import Profile from "../pages/Profile/Profile"; import EditProfile from "../pages/EditProfile/EditProfile"; import Programme from "../pages/Programme/Programme"; import Courses from "../pages/Courses/Courses"; import NotesLibrary from "../pages/NotesLibrary/NotesLibrary"; import Events from "../pages/Events/Events"; import Announcements from "../pages/Announcements/Announcements"; import Assignments from "../pages/Assignments/Assignments"; import Timetable from "../pages/Timetable/Timetable"; import Attendance from "../pages/Attendance/Attendance"; import Communities from "../pages/Communities/Communities"; import DepartmentFeed from "../pages/DepartmentFeed/DepartmentFeed"; import Faculty from "../pages/Faculty/Faculty"; import Clubs from "../pages/Clubs/Clubs"; import SubmitContent from "../pages/SubmitContent/SubmitContent"; import SavedContent from "../pages/SavedContent/SavedContent"; import Notifications from "../pages/Notifications/Notifications"; import Reports from "../pages/Reports/Reports"; import Admin from "../pages/Admin/Admin"; import ManageUsers from "../pages/ManageUsers/ManageUsers"; import AcademicMaster from "../pages/AcademicMaster/AcademicMaster"; import MarkAttendance from "../pages/MarkAttendance/MarkAttendance"; import AdminTimetable from "../pages/AdminTimetable/AdminTimetable"; import TeacherCharges from "../pages/TeacherCharges/TeacherCharges"; import FacultyRequests from "../pages/FacultyRequests/FacultyRequests"; import MyCharges from "../pages/MyCharges/MyCharges"; import AuditLogs from "../pages/AuditLogs/AuditLogs"; import Forbidden from "../pages/Forbidden/Forbidden"; import CourseDetail from "../pages/CourseDetail/CourseDetail"; import SubjectMaster from "../pages/SubjectMaster";
const PrivateRoute = ({ children }) => { const { user } = useContext(AuthContext); return user ? children : <Navigate to="/login" replace />; };
const RoleRoute = ({ children, allowed }) => { const { user } = useContext(AuthContext); return allowed.includes(user?.role) ? children : <Navigate to="/forbidden" replace />; };
const AdminRoute = ({ children }) => <RoleRoute allowed={["student_admin", "teacher_admin", "hod", "edp", "super_admin"]}>{children}</RoleRoute>;
const AcademicStaffRoute = ({ children }) => <RoleRoute allowed={["teacher", "teacher_admin", "hod", "super_admin"]}>{children}</RoleRoute>;
const TimetableManagerRoute = ({ children }) => <RoleRoute allowed={["hod", "super_admin"]}>{children}</RoleRoute>;
const SuperAdminRoute = ({ children }) => <RoleRoute allowed={["super_admin"]}>{children}</RoleRoute>;
const SubjectManagerRoute = ({ children }) => <RoleRoute allowed={["hod", "edp", "super_admin"]}>{children}</RoleRoute>;
const ProfileRoute = ({ children }) => <RoleRoute allowed={["student", "student_admin", "teacher", "teacher_admin", "hod", "edp", "super_admin"]}>{children}</RoleRoute>;
const AppRoutes = () => <Routes>
  <Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} />
  <Route element={<PrivateRoute><PortalLayout /></PrivateRoute>}>
    <Route path="/" element={<Home />} /><Route path="/dashboard" element={<Dashboard />} /><Route path="/profile" element={<Profile />} /><Route path="/edit-profile" element={<ProfileRoute><EditProfile /></ProfileRoute>} /><Route path="/programme" element={<Programme />} /><Route path="/courses" element={<Courses />} /><Route path="/courses/:subject" element={<CourseDetail />} /><Route path="/notes" element={<NotesLibrary />} /><Route path="/events" element={<Events />} /><Route path="/announcements" element={<Announcements />} /><Route path="/assignments" element={<Assignments />} /><Route path="/timetable" element={<Timetable />} /><Route path="/attendance" element={<Attendance />} /><Route path="/communities" element={<Communities />} /><Route path="/department/:department" element={<DepartmentFeed />} /><Route path="/faculty" element={<Faculty />} /><Route path="/clubs" element={<Clubs />} /><Route path="/submit" element={<SubmitContent />} /><Route path="/saved" element={<SavedContent />} /><Route path="/notifications" element={<Notifications />} /><Route path="/reports" element={<Reports />} />
    <Route path="/admin" element={<AdminRoute><Admin /></AdminRoute>} /><Route path="/manage-users" element={<AdminRoute><ManageUsers /></AdminRoute>} /><Route path="/academic-master" element={<SuperAdminRoute><AcademicMaster /></SuperAdminRoute>} /><Route path="/subject-master" element={<SubjectManagerRoute><SubjectMaster /></SubjectManagerRoute>} /><Route path="/mark-attendance" element={<AcademicStaffRoute><MarkAttendance /></AcademicStaffRoute>} /><Route path="/admin-timetable" element={<TimetableManagerRoute><AdminTimetable /></TimetableManagerRoute>} /><Route path="/teacher-charges" element={<TimetableManagerRoute><TeacherCharges /></TimetableManagerRoute>} /><Route path="/faculty-requests" element={<TimetableManagerRoute><FacultyRequests /></TimetableManagerRoute>} /><Route path="/my-charges" element={<AdminRoute><MyCharges /></AdminRoute>} /><Route path="/audit-logs" element={<SuperAdminRoute><AuditLogs /></SuperAdminRoute>} /><Route path="/forbidden" element={<Forbidden />} />
  </Route>
  <Route path="*" element={<Navigate to="/" replace />} />
</Routes>;
export default AppRoutes;
