import AcademicMaster from "../models/AcademicMaster.js";
import Community from "../models/Community.js";
import User from "../models/User.js";

const normalize = (value = "") =>
  String(value)
    .trim()
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const toTitle = (value = "") =>
  String(value)
    .trim()
    .replace(/\s+/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());

export const getCommunities = async (req, res) => {
  const [savedCommunities, academicDepartments, userDepartments] = await Promise.all([
    Community.find().sort({ name: 1 }),
    AcademicMaster.find({ type: "department", isActive: true }).sort({ name: 1 }),
    User.distinct("department", { department: { $nin: [null, ""] } }),
  ]);

  const communityMap = new Map();

  const put = (department, source = "department") => {
    const cleanDepartment = toTitle(department);
    const key = normalize(cleanDepartment);
    if (!key || communityMap.has(key)) return;

    communityMap.set(key, {
      _id: `department-${key.replace(/\s+/g, "-")}`,
      name: cleanDepartment,
      department: cleanDepartment,
      description: `Verified academic updates and activities for ${cleanDepartment}.`,
      members: [],
      isAutoGenerated: true,
      source,
    });
  };

  academicDepartments.forEach((item) => put(item.name, "academic-master"));
  userDepartments.forEach((department) => put(department, "users"));

  savedCommunities.forEach((community) => {
    const key = normalize(community.department || community.name);
    communityMap.set(key, {
      ...community.toObject(),
      name: community.name || community.department,
      department: community.department || community.name,
      isAutoGenerated: false,
      source: "community",
    });
  });

  res.json([...communityMap.values()].sort((a, b) => String(a.name).localeCompare(String(b.name))));
};

export const createCommunity = async (req, res) => {
  const department = toTitle(req.body.department || req.body.name);
  const name = toTitle(req.body.name || department);

  const community = await Community.create({
    ...req.body,
    name,
    department,
    createdBy: req.user._id,
  });

  res.status(201).json(community);
};

export const joinCommunity = async (req, res) => {
  const community = await Community.findById(req.params.id);
  if (!community) return res.status(404).json({ message: "Community not found" });
  if (!community.members.some((id) => String(id) === String(req.user._id))) community.members.push(req.user._id);
  await community.save();
  res.json(community);
};
