import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getCommunities } from "../../api/communityApi";
import "./Communities.css";

const Communities = () => {
  const [communities, setCommunities] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let active = true;

    getCommunities()
      .then((data) => {
        if (!active) return;
        setCommunities(Array.isArray(data) ? data : []);
        setError("");
      })
      .catch(() => {
        if (!active) return;
        setCommunities([]);
        setError("Unable to load department communities. Please check backend connection.");
      })
      .finally(() => active && setLoading(false));

    return () => {
      active = false;
    };
  }, []);

  return (
    <div className="communities-page">
      <div className="breadcrumb">Home / Communities</div>

      <section className="communities-header">
        <span>Department Communities</span>
        <h1>Choose Department</h1>
        <p>
          Communities are now generated from Academic Master and user departments, so every new
          department automatically appears here after it is added.
        </p>
      </section>

      {loading && <div className="empty-card">Loading communities...</div>}
      {error && <div className="empty-card error-card">{error}</div>}

      {!loading && !error && communities.length === 0 && (
        <div className="empty-card">
          No department found yet. Add departments from Academic Master to create communities automatically.
        </div>
      )}

      <section className="communities-grid">
        {communities.map((community) => {
          const department = community.department || community.name;
          return (
            <article className="community-card" key={community._id || department}>
              <div className="community-card-top">
                <span>{community.isAutoGenerated ? "Auto" : "Custom"}</span>
              </div>
              <h2>{department}</h2>
              <p>{community.description || `Verified academic updates and activities for ${department}.`}</p>
              <Link to={`/department/${encodeURIComponent(department)}`}>
                <button>Open Feed</button>
              </Link>
            </article>
          );
        })}
      </section>
    </div>
  );
};

export default Communities;
