import React, { useContext, useEffect, useMemo, useState } from "react";
import { AuthContext } from "../../context/AuthContext";
import { getAcademicOptions } from "../../api/academicApi";
import { createTimetableEntry, deleteTimetableEntry, getMyTimetable, getTimetable, updateTimetableEntry } from "../../api/timetableApi";
import { scopedProgrammes, scopedSemesters, scopedSubjects, scopedYears, uniqueNames, validateAcademicCombination } from "../../utils/academicScope";
import "./Timetable.css";
const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const fallbackSections = ["A", "B", "C"];
const groupTypes = [["full_section", "Full Section"], ["sub_group", "Sub Group"], ["lab_batch", "Lab Batch"], ["elective", "Elective"], ["specialization", "Specialization"]];
const emptyForm = { department:"", programme:"", year:"", semester:"", section:"A", groupType:"full_section", groupName:"All", day:"Monday", startTime:"", endTime:"", subject:"", facultyName:"", room:"" };
const SelectField = ({ label, value, onChange, options = [], required = false }) => { const safeOptions = value && !options.includes(value) ? [value, ...options] : options; return <label className="field-label"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} required={required}><option value="">Select {label}</option>{safeOptions.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; };
const prettyGroup = (entry) => `${entry.groupType || "full_section"}: ${entry.groupName || "All"}`.replace("full_section", "full section").replace("sub_group", "sub group").replace("lab_batch", "lab batch");
const Timetable = () => {
  const { user } = useContext(AuthContext);
  const canManage = ["hod", "super_admin"].includes(user?.role);
  const canFilter = ["hod", "super_admin"].includes(user?.role);
  const [items, setItems] = useState([]); const [academicOptions, setAcademicOptions] = useState([]); const [loading, setLoading] = useState(false); const [editingId, setEditingId] = useState(null);
  const [filters, setFilters] = useState({ department:user?.department || "", programme:user?.programme || "", year:user?.year || "", semester:user?.semester || "", section:user?.section || "A", groupType:"", groupName:"" });
  const [form, setForm] = useState({ ...emptyForm, department:user?.department || "", programme:user?.programme || "", year:user?.year || "", semester:user?.semester || "", section:user?.section || "A" });
  const departments = useMemo(() => uniqueNames(academicOptions, "department"), [academicOptions]);
  const filterProgrammes = useMemo(() => scopedProgrammes(academicOptions, filters.department), [academicOptions, filters.department]);
  const filterYears = useMemo(() => scopedYears(academicOptions, filters.programme), [academicOptions, filters.programme]);
  const filterSemesters = useMemo(() => scopedSemesters(academicOptions, filters.programme, filters.year), [academicOptions, filters.programme, filters.year]);
  const formProgrammes = useMemo(() => scopedProgrammes(academicOptions, form.department), [academicOptions, form.department]);
  const formYears = useMemo(() => scopedYears(academicOptions, form.programme), [academicOptions, form.programme]);
  const formSemesters = useMemo(() => scopedSemesters(academicOptions, form.programme, form.year), [academicOptions, form.programme, form.year]);
  const subjects = useMemo(() => scopedSubjects(academicOptions, form), [academicOptions, form]);
  const sections = useMemo(() => { const masterSections = uniqueNames(academicOptions, "section"); return masterSections.length ? masterSections : fallbackSections; }, [academicOptions]);
  const clean = (source={}) => Object.fromEntries(Object.entries(source).filter(([,v]) => v && v !== "all" && v !== "All"));
  const load = async (activeFilters = filters) => { setLoading(true); try { setItems(canFilter ? await getTimetable(clean(activeFilters)) : await getMyTimetable()); } catch(e){ console.error(e); setItems([]); } finally { setLoading(false); } };
  useEffect(() => { (async()=>{ const options=await getAcademicOptions(); setAcademicOptions(options); await load(filters); })(); /* eslint-disable-next-line */ }, []);
  const updateFilter = (key, value) => setFilters((current) => { const next={...current,[key]:value}; if(key==="department"){next.programme="";next.year="";next.semester="";} if(key==="programme"){next.year="";next.semester="";} if(key==="year") next.semester=""; return next; });
  const updateForm = (key, value) => setForm((current) => { const next={...current,[key]:value}; if(key==="department"){next.programme="";next.year="";next.semester="";next.subject="";} if(key==="programme"){next.year="";next.semester="";next.subject="";} if(key==="year"){next.semester="";next.subject="";} if(key==="semester") next.subject=""; if(key==="groupType" && value==="full_section") next.groupName="All"; return next; });
  const submit = async (event) => { event.preventDefault(); const err=validateAcademicCombination(form, academicOptions); if(err) return alert(err); try { const saved = editingId ? await updateTimetableEntry(editingId, form) : await createTimetableEntry(form); alert(editingId ? "Timetable entry updated" : "Timetable entry added"); const nextFilters={department:saved.department, programme:saved.programme, year:saved.year, semester:saved.semester, section:saved.section, groupType:"", groupName:""}; setFilters(nextFilters); setEditingId(null); setForm({ ...emptyForm, ...nextFilters, day:"Monday", startTime:"", endTime:"", subject:"", facultyName:"", room:"" }); await load(nextFilters); } catch(error){ alert(error.response?.data?.message || "Timetable save failed"); } };
  const startEdit = (entry) => { setEditingId(entry._id); setForm({ ...emptyForm, ...entry, facultyName: entry.facultyName || entry.faculty?.name || "" }); window.scrollTo({top:0, behavior:"smooth"}); };
  const timeSlots = useMemo(() => Array.from(new Set(items.map((i)=>`${i.startTime} - ${i.endTime}`))).sort(), [items]);
  const cellFor = (day, slot) => items.filter((item)=>item.day===day && `${item.startTime} - ${item.endTime}`===slot);
  return <main className="feature-page timetable-page"><section className="feature-hero"><span>Timetable</span><h1>Weekly timetable grid</h1><p>HOD and Super Admin can edit timetable. Students and teachers see only their relevant full-section, subgroup, lab, elective or specialization classes.</p></section>
    <section className="feature-panel compact-panel"><div className="panel-heading"><div><h2>{canFilter ? "Load timetable" : "My timetable"}</h2><p>{canFilter ? "Filter exact academic scope. HOD sees department scope; teachers see their classes from My Timetable." : "Loaded from your profile and group/elective allocation."}</p></div></div>{canFilter ? <div className="feature-form timetable-filter-form"><SelectField label="Department" value={filters.department} onChange={(v)=>updateFilter("department",v)} options={departments}/><SelectField label="Programme" value={filters.programme} onChange={(v)=>updateFilter("programme",v)} options={filterProgrammes}/><SelectField label="Year" value={filters.year} onChange={(v)=>updateFilter("year",v)} options={filterYears}/><SelectField label="Semester" value={filters.semester} onChange={(v)=>updateFilter("semester",v)} options={filterSemesters}/><SelectField label="Section" value={filters.section} onChange={(v)=>updateFilter("section",v)} options={sections}/><button type="button" onClick={()=>load(filters)}>{loading ? "Loading..." : "Load"}</button></div> : <div className="student-timetable-summary"><span>{user?.department||"Department not set"}</span><span>{user?.programme||"Programme not set"}</span><span>{user?.year||"Year not set"}</span><span>{user?.semester||"Semester not set"}</span><span>Section {user?.section||"not set"}</span><span>{user?.groupName || user?.electiveGroup || user?.specialization || "Full section"}</span><button type="button" onClick={()=>load(filters)}>{loading ? "Refreshing..." : "Refresh"}</button></div>}</section>
    {canManage && <section className="feature-panel"><div className="panel-heading"><div><h2>{editingId ? "Edit class" : "Add class"}</h2><p>Only HOD/Super Admin can manage timetable. Use group type for lab batches, sub groups, electives and specializations.</p></div>{editingId && <button className="feature-btn alt" onClick={()=>{setEditingId(null);setForm(emptyForm)}}>Cancel Edit</button>}</div><form className="feature-form timetable-add-form" onSubmit={submit}><SelectField label="Department" value={form.department} onChange={(v)=>updateForm("department",v)} options={departments} required/><SelectField label="Programme" value={form.programme} onChange={(v)=>updateForm("programme",v)} options={formProgrammes} required/><SelectField label="Year" value={form.year} onChange={(v)=>updateForm("year",v)} options={formYears} required/><SelectField label="Semester" value={form.semester} onChange={(v)=>updateForm("semester",v)} options={formSemesters} required/><SelectField label="Section" value={form.section} onChange={(v)=>updateForm("section",v)} options={sections} required/><label className="field-label"><span>Group Type</span><select value={form.groupType} onChange={(e)=>updateForm("groupType",e.target.value)}>{groupTypes.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="field-label"><span>Group Name</span><input value={form.groupName} onChange={(e)=>updateForm("groupName",e.target.value)} placeholder="All / A1 / Lab-1 / Elective-1" required/></label><SelectField label="Day" value={form.day} onChange={(v)=>updateForm("day",v)} options={days} required/><label className="field-label"><span>Start Time</span><input type="time" value={form.startTime} onChange={(e)=>updateForm("startTime",e.target.value)} required/></label><label className="field-label"><span>End Time</span><input type="time" value={form.endTime} onChange={(e)=>updateForm("endTime",e.target.value)} required/></label>{subjects.length ? <SelectField label="Subject" value={form.subject} onChange={(v)=>updateForm("subject",v)} options={subjects} required/> : <label className="field-label"><span>Subject</span><input value={form.subject} onChange={(e)=>updateForm("subject",e.target.value)} required/></label>}<label className="field-label"><span>Faculty</span><input value={form.facultyName} onChange={(e)=>updateForm("facultyName",e.target.value)} placeholder="Faculty name"/></label><label className="field-label"><span>Room</span><input value={form.room} onChange={(e)=>updateForm("room",e.target.value)} placeholder="Room"/></label><button className="submit-class-btn">{editingId ? "Update Class" : "Add Class"}</button></form></section>}
    <section className="feature-panel timetable-grid-panel"><div className="panel-heading"><div><h2>Weekly grid</h2><p>Shows classes in proper tabular format. Multiple elective/specialization classes can appear in the same time slot.</p></div></div><div className="timetable-grid-scroll"><table className="weekly-timetable"><thead><tr><th>Time</th>{days.map(day=><th key={day}>{day}</th>)}</tr></thead><tbody>{timeSlots.length ? timeSlots.map(slot=><tr key={slot}><th>{slot}</th>{days.map(day=><td key={day}>{cellFor(day,slot).map(entry=><div className="grid-class" key={entry._id}><b>{entry.subject}</b><span>{prettyGroup(entry)}</span><small>{entry.facultyName || entry.faculty?.name || "Faculty"} • {entry.room || "TBA"}</small>{canManage && <div className="grid-actions"><button onClick={()=>startEdit(entry)}>Edit</button><button onClick={()=>deleteTimetableEntry(entry._id).then(()=>load(filters))}>Delete</button></div>}</div>)}</td>)}</tr>) : <tr><td colSpan="7" className="empty-cell">No timetable found for this scope.</td></tr>}</tbody></table></div></section>
  </main>;
};
export default Timetable;
